POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "firstName": "Renato",
    "lastName": "Vicente",
    "email": "rntvicente@gmail.com",
    "password": "P4ssW@rd"
}

###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "rntvicente@gmail.com.br",
    "password": "P4ssWrd"
}